#### general settings
name: latent-low
use_tb_logger: true
model: latent_low
distortion: low
gpu_ids: [0]

sde:
  max_sigma: 50
  T: 100
  sample_T: 100
  schedule: cosine # linear, cosine
  eps: 0.005

degradation: # for some synthetic dataset that only have GTs
  # for denoising
  sigma: 25
  noise_type: G # Gaussian noise: G

  # for super-resolution
  scale: 4
  
#### datasets
datasets:
  train:
    name: Train_Dataset
    mode: LQGTR
    dataroot_GT: ./codes/config/latent-low/dataset/train/gt
    dataroot_LQ: ./codes/config/latent-low/dataset/train/input
    dataroot_R: ./codes/config/latent-low/dataset/train/reflectance

    use_shuffle: true
    n_workers: 2  # per GPU
    batch_size: 8
    GT_size: 400
    LR_size: 400
    R_size: 400
    use_flip: true
    use_rot: true
    use_swap: false
    color: RGB
  val:
    name: Val_Dataset
    mode: LQGTR
    dataroot_GT: ./codes/config/latent-low/dataset/val/gt
    dataroot_LQ: ./codes/config/latent-low/dataset/val/input
    dataroot_R: ./codes/config/latent-low/dataset/val/reflectance


#### network structures
network_G:
  which_model: ConditionalNAFNet
  setting:
    img_channel: 8
    width: 64
    enc_blk_nums: [1, 1, 1, 28]
    middle_blk_num: 1
    dec_blk_nums: [1, 1, 1, 1]

network_L:
  which_model: UNet
  setting:
    in_ch: 3
    out_ch: 3
    ch: 8
    ch_mult: [4, 8, 16]
    embed_dim: 8

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~
  pretrain_model_L: ~

#### training settings: learning rate scheme, loss
train:
  optimizer: Lion
  lr_G: !!float 4e-5
  lr_scheme: TrueCosineAnnealingLR
  beta1: 0.9
  beta2: 0.99
  niter: 210000
  warmup_iter: -1  # no warm up
  lr_steps: [200000, 400000, 600000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 73
  val_freq: !!float 5e3
#  val_freq: 10

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
